name: Ray Baldino Photographer
favicon: null
layout_spectrum: 0.49737
typography_spectrum: 0.27893
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f2f0'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
