name: Ray Baldino Photographer
favicon: null
layout_spectrum: 0
typography_spectrum: 0.27893
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#4a333e'
    - '#8791a6'
    - '#745e54'
    - '#0076d3'
  brandStrength: 0.375
  lightness: 0.9375
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
